[package]
name = "merkle_proof"
version = "0.1.0"
authors = ["Michael Sproul <michael@sigmaprime.io>"]
edition = "2018"

[dependencies]
ethereum-types = "0.5"
lazy_static = "1.3.0"
hashing = { path = "../hashing" }

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"
