[package]
name = "kzg"
version = "0.1.0"
authors = ["Pawan Dhananjay <pawandhananjay@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethereum_ssz = "0.5.0"
ethereum_ssz_derive = "0.5.0"
tree_hash = "0.5.0"
derivative = "2.1.1"
serde = "1.0.116"
serde_derive = "1.0.116"
ethereum_serde_utils = "0.5.0"
hex = "0.4.2"
ethereum_hashing = "1.0.0-beta.2"
c-kzg = { git = "https://github.com/realbigsean/c-kzg-4844", rev = "1f25100d889c1dcc221f0c624225b38d511387a2" , features = ["mainnet-spec"]}
c_kzg_min = { package = "c-kzg", git = "https://github.com/realbigsean//c-kzg-4844", rev = "1f25100d889c1dcc221f0c624225b38d511387a2", features = ["minimal-spec"] }
arbitrary = { version = "1.0", features = ["derive"], optional = true }

[features]
default = ["mainnet-spec"]
mainnet-spec = ["c-kzg/mainnet-spec"]
minimal-spec = ["c-kzg/minimal-spec"]