on:
  workflow_call:
    inputs:
      enabled:
        default: true
runs:
  using: composite
  steps:
    - uses: rui314/setup-mold@v1
      with:
        make-default: false
      if: "${{ runner.os == 'linux' && inputs.enabled == 'true' }}"
    - run: echo "hello from mold action"
      shell: bash
      if: "${{ runner.os == 'linux' && inputs.enabled == 'true' }}"
    - run: mold --version
      shell: bash
    - run: echo "RUSTFLAGS=-C linker=clang -C link-arg=-fuse-ld=/usr/local/bin/mold ${{ env.RUSTFLAGS }}" >> $GITHUB_ENV
      shell: bash
      if: "${{ runner.os == 'linux' && inputs.enabled == 'true' }}"
